config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  constraints(lambda { |request| request.subdomain.empty? or request.subdomain == 'www' }) do
    resources :communities,
              :only => [:index, :new, :create]

    root 'pages#home'
  end

  # *.inspiredcauses.com => Campaign Subdomains
  constraints(lambda { |request| request.subdomain != 'www' }) do
    resources :people do
      resources :notes,
                :except => [:update, :edit]
      
      resources :messages,
                :only => [:index, :show]
    end

    resources :companies do
      resources :notes,
                :except => [:update, :edit]
    end

    resources :messages,
              :except => [:edit, :update, :destroy]

    resources :digital_addresses,
              :only => [:destroy]

    resources :communities,
              :only => [:show, :update] do
      resources :notes,
                :except => [:update, :edit]
    end

    get '/edit', to: 'communities#edit', as: :owner_edit_community
    root :to => "communities#show", as: :community_home
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
	extend FriendlyId
  friendly_id :name, use: [:slugged, :history, :scoped], :scope => :community
  
  belongs_to :address
  belongs_to :community
  
	has_many :digital_addresses, as: :addressable, :dependent => :destroy
	has_many :employments
	has_many :companies, through: :employments
	has_many :message_recipients
	has_many :messages, through: :message_recipients
	has_many :notes, as: :noteable, :dependent => :destroy

	accepts_nested_attributes_for :address
	accepts_nested_attributes_for :companies
	accepts_nested_attributes_for :digital_addresses
	accepts_nested_attributes_for :employments

	validates_presence_of :name,
												:community_id

	mount_uploader :photo, ProfilePhotoUploader

	GENDER_MALE			 = 1
	GENDER_FEMALE 	 = 2

	def self.genders
    {
			Person::GENDER_MALE			  => 'Male',
			Person::GENDER_FEMALE		  => 'Female',
		}
	end

	def gender_to_string
		case gender
			when GENDER_MALE
				"Male"
			when GENDER_FEMALE
				"Female"
		end
	end

	def first_name
    name.scan(/\w+/).first
  end

  def email
  	if digital_addresses.where(:address_type => 2).first
  		digital_addresses.where(:address_type => 2).first.url
  	else
  		return nil
  	end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!
  before_action :load_community_from_subdomain
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  add_breadcrumb "Home", :community_home_path

  # GET /people
  # GET /people.json
  def index
    if params[:person_type] == "customers"
      @search = @community.people.where(:is_employee => false).search(params[:q])
    elsif params[:person_type] == "coworkers"
      @search = @community.people.where(:is_employee => true).search(params[:q])
    else
      @search = @community.people.search(params[:q])
    end
      @people = @search.result

    @tab_name         = "people"
    @page_title       = "People"
    @page_subtitle    = "Emotional Connections"
    @page_description = ""

    add_breadcrumb "People", people_path, :title => "#{@community.name} People"
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @noteable   = @person
    @note       = @person.notes.new
    @notes      = @person.notes.order("created_at desc")
    @messages   = @person.messages.order("created_at desc")

    @tab_name         = "people"
    @page_title       = "#{@person.name}"
    @page_subtitle    = "Connected on #{@person.created_at.strftime("%b %e, %Y")}"
    @page_description = ""

    add_breadcrumb "People", people_path, :title => "#{@community.name} People"
    add_breadcrumb "#{@person.name}", person_path(@person), :title => "#{@person.name} within #{@community.name}"
  end

  # GET /people/new
  def new
    @person = @community.people.new
    @person.build_address
    @person.digital_addresses.build
    @person.companies.build
    @person.employments.build
    
    @tab_name         = "people"
    @page_title       = "New Person"
    @page_subtitle    = ""
    @page_description = ""

    add_breadcrumb "People", people_path, :title => "#{@community.name} People"
    add_breadcrumb "New", new_person_path, :title => "New People"
  end

  # GET /people/1/edit
  def edit
    @person.companies.build
    unless @person.employments.present?
      @person.employments.build
    end
    
    unless @person.address.present?
      @person.build_address
    end

    @tab_name         = "people"
    @page_title       = "Edit #{@person.name}"
    @page_subtitle    = "Update Person Information"
    @page_description = ""

    add_breadcrumb "People", people_path, :title => "#{@community.name} People"
    add_breadcrumb "#{@person.name}", person_path(@person), :title => "#{@person.name} within #{@community.name}"
    add_breadcrumb "Edit", edit_person_path(@person), :title => "Edit #{@person.name} within #{@community.name}"
  end

  # POST /people
  # POST /people.json
  def create
    @person = @community.people.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_path(@person), notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_path(@person), notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = @community.people.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name,
                                     :bio,
                                     :is_employee,
                                     :date_of_birth,
                                     :gender,
                                     :photo,
                                     :remote_photo_url,
                                     :slug,
                                     companies_attributes: [:id, :name],
                                     digital_addresses_attributes: [:id, :name, :address_type, :url],
                                     employments_attributes: [:id, :company_id, :role],
                                     address_attributes: [:id, :street_line_1, :street_line_2, :city, :state, :zip])
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= simple_form_for(@person, :html => {:multipart => true}) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-md-6">

      <legend>General Info</legend>
      <%= f.input :is_employee, :label => "Your Coworker" %>
      <%= f.input :name %>
      <%= f.input :bio %>
      <%= f.input :gender, as: :check_boxes, collection: (Person.genders), label_method: :last, value_method: :first %>
      <%= f.input :date_of_birth, input_html: { :class => "form-control"}, :include_blank => true, :default => nil, ampm: true, :order => [:month, :day,:year], start_year: Time.now.year - 90 %>

      <div class="row">
        <div class="col-md-6">
          <%= f.input :photo, :label => "Upload Photo from File" %>
          <%= f.hidden_field :photo_cache %>
        </div>
        <div class="col-md-6">
          <%= f.input :remote_photo_url, :label => "or from URL (http://...)" %>
        </div>
      </div>

      <legend>Physical Address</legend>
      <%= f.association :address do |a| %>
        <div class="row">
          <div class="col-md-12">
            <%= a.input :street_line_1 %>
          </div>
          <div class="col-md-12">
            <%= a.input :street_line_2 %>
          </div>
          <div class="col-md-5">
            <%= a.input :city, :placeholder => "Atlanta" %>
          </div>
          <div class="col-md-4">
            <%= a.input :state, collection: (Address.states), input_html: { :class => "form-control"}, :prompt => 'State...' %>
          </div>
          <div class="col-md-3">
            <%= a.input :zip, :placeholder => "30303" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-6">
      <legend>Digital Addresses</legend>
      <div class="">
        <table id="digital_address_table" class="full_width">
          <tr>
            <th>Reference</th>
            <th>Type</th>
            <th class="remove_button_column"></th>
          </tr>
          <%= f.association :digital_addresses do |d_address| %>
            <tr>
              <td><%= d_address.input :url, label: false, :placeholder => "you@example.com" %></td>
              <td><%= d_address.input :address_type, collection: (DigitalAddress.address_types), label_method: :last, value_method: :first, input_html: { :class => "form-control"}, :label => false %></td>
              <td></td>
            </tr>
          <% end %>
        </table>
        <div class="text-right">
          <%= link_to "", :onClick => "return false;", :id => "add_web_button", :class => "btn btn-sm btn-default pull-right" do %>
            <div class="glyphicon glyphicon-plus"></div> Add Another
          <% end %>
        </div>
      </div>

      <legend>Employment</legend>
      <div class="">
        <table id="employment_table" class="full_width">
          <tr>
            <th>Company</th>
            <th>Role</th>
            <th class="remove_button_column"></th>
          </tr>
          <%= f.association :employments do |e| %>
            <tr>
              <td><%= e.input :company_id, collection: (@community.companies.all), label_method: :name, value_method: :id, :label => false, input_html: { :class => "form-control"} %></td>
              <td><%= e.input :role, :label => false %></td>
            </tr>
          <% end %>
        </table>
        <div class="text-right">
          <%= link_to "", :onClick => "return false;", :id => "add_company", :class => "btn btn-sm btn-default pull-right" do %>
            <div class="glyphicon glyphicon-plus"></div> Add Another
          <% end %>
        </div>
      </div>

      <br>

      <div class="form-actions">
        <% if @person.id %>
          <%= link_to 'Delete Person', person_path(@person), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn text-danger pull-left" %>
        <% else %>
          <%= link_to 'Cancel Person', people_path,  data: { confirm: 'Are you sure? All information will be lost, FOREVER!' }, :class => "btn text-danger pull-left" %>
        <% end %>
        <%= f.button :submit, :class => "btn btn-primary pull-right" %>
      </div>
    </div>
  </div>
<% end %>

<%= content_for :page_script do %>
  <script type="text/javascript">
    // Add Digital Address Script
    $(document).ready(function(){
      var i = <%= @person.digital_addresses.count %>;
      var options = '<%= raw options_from_collection_for_select(DigitalAddress.address_types, :first, :last).squish.gsub('> <', '><') %>';

      $("#add_web_button").click(function(){
        i ++;
        $("#digital_address_table").append('<tr id="digi_'+i+'""><td><div class="input url optional person_digital_addresses_url"><input class="string url optional" id="person_digital_addresses_attributes_'+i+'_url" name="person[digital_addresses_attributes]['+i+'][url]" type="url" value="http://"></div></td><td><select id="person_digital_addresses_attributes_'+i+'_address_type" name="person[digital_addresses_attributes]['+i+'][address_type]" class="form-control">' + options + '</select></td><td><div class="remove_column">x</div></td></tr>');
      });
    });
  </script>

  <script type="text/javascript">
    // Add Digital Address Script
    $(document).ready(function(){
      var i = <%= @person.companies.count %>;
      var options = '<%= raw options_from_collection_for_select(@community.companies.all, :id, :name).squish.gsub('> <', '><') %>';

      $("#add_company").click(function(){
        i ++;
        $("#employment_table").append('<tr><td><div class="input select optional person_employments_company_id"><select class="select optional form-control" id="person_employments_attributes_'+i+'_company_id" name="person[employments_attributes]['+i+'][company_id]">' + options + '</select></div></td><td><div class="input string optional person_employments_role"><input class="string optional" id="person_employments_attributes_'+i+'_role" name="person[employments_attributes]['+i+'][role]" type="text" value=""></div></td><td><div class="remove_column">x</div></td></tr>');
      });
    });
  </script>
  <script type="text/javascript">

    // Remove Row Script
    $(document).ready(function(){
      $('table').on('click', '.remove_column', function(e){
         $(this).closest('tr').remove()
      })
     });
  </script>
<% end %>

app/views/people/_index_nav.html.erb
<div>
  <ul class="nav nav-pills">
    <li class="pull-right <%= "active" unless params[:person_type] %>">
      <%= link_to "All",  url_for(:person_type => nil) %>
    </li>
    <li class="pull-right <%= "active" if params[:person_type] == "customers" %>">
      <%= link_to "Customers",  url_for(:person_type => "customers") %>
    </li>
    <li class="pull-right <%= "active" if params[:person_type] == "coworkers" %>">
      <%= link_to "Coworkers",  url_for(:person_type => "coworkers") %>
    </li>
  </ul>
  <br>
</div>

app/views/people/_person.html.erb
<%= render partial: "shared/asset_preview", locals: {:asset => person} %>

app/views/people/_tabs.html.erb
<!-- Nav tabs -->
<ul class="nav nav-tabs">
  <li class="active"><a href="#notes" data-toggle="tab"><div class="icon-noteslist"></div> Notes</a></li>
  <li><a href="#messages" data-toggle="tab"><div class="icon-inbox"></div> Messages</a></li>
  <% if @person.address.city.present? %>
    <li><a href="#address" data-toggle="tab"><div class="icon-map-marker"></div> Address</a></li>
  <% end %>
  <li class="pull-right"><%= link_to "Edit #{@person.first_name}'s Info", edit_person_path(@person) %></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div class="tab-pane active" id="notes">
    <div class="row">
      <div class="col-sm-6 col-md-7">
        <%= render @notes.last(5) if @notes %>
  
        <% if @notes.count == 0 %>
          <div class="text-center">
            <p>There are currently no notes for <%= @person.first_name %>.</p>
          </div>
        <% else %>
          <div class="text-center">
            <%= link_to "View All #{@person.first_name}'s Notes", person_notes_url(@person), :class => "btn btn-link" %>
          </div>
        <% end %>

      </div>
      <div class="col-sm-6 col-md-5">
        <div class="new_note_wrapper">
          <h3 class="new_note_heading">New Note</h3>
          <%= render "notes/form" %>
        </div>
      </div>
    </div>

  </div>
  <div class="tab-pane" id="messages">
    <div class="text-right">
      <%= link_to "New Message", new_message_path(:message_to => @person.id), :class => "btn btn-primary" %><br><br>
    </div>
    
    <%= render @messages %>

    <% if @messages.count == 0 %>
      <div class="text-center">
        <p>There are currently no messages for <%= @person.first_name %>.</p>
      </div>
    <% else %>
      <div class="text-center">
        <%= link_to "View All #{@person.first_name}'s Messages", person_messages_url(@person), :class => "btn btn-link" %>
      </div>
    <% end %>

  </div>
  <% if @person.address.present? %>
    <div class="tab-pane" id="address">
      <% if @person.address.city.present? %>
        <%= image_tag @person.address.map %>
        <br><br>
        <pre><%= @person.address.mappable_address %></pre>
      <% end %>
    </div>
  <% end %>
</div>

app/views/people/edit.html.erb
<%= render 'form' %>

app/views/people/index.html.erb
<div class="row">
  <div class="col-sm-4">
    <%= render "shared/search" %>
  </div>
  <div class="col-sm-8">
    <div class="btn-group pull-right">
      <%= link_to new_person_path, :class => "btn btn-primary" do %>
        <div class="icon-plus"></div> New Person
      <% end %>
      <%= link_to "", :class => "btn btn-primary" do %>
        <div class="icon-export"></div> Export
      <% end %>
      <%= link_to "", :class => "btn btn-primary" do %>
        <div class="icon-import"></div> Import
      <% end %>
    </div>
  </div>
</div>

<hr>

<%= render "people/index_nav" %>

<div class="row">
  <% if @people.count > 0 %>
    <%= render @people.order("name asc") %>
  <% else %>
    <div class="text-center">
      <p>There are currently no people in the <%= @community.name %> Community.</p>
      <p><%= link_to "Add a Person", new_person_path %></p>
    </div>
  <% end %>
</div>

app/views/people/new.html.erb
<%= render 'form' %>

app/views/people/show.html.erb
<div class="row">
  <div class="col-sm-6 col-md-3">
    <%= render partial: "shared/asset_details", locals: {:asset => @person} %>
  </div>

  <div class="col-sm-6 col-md-9">
    <%= render "people/tabs" %>
  </div>
</div>