config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  constraints(lambda { |request| request.subdomain.empty? or request.subdomain == 'www' }) do
    resources :communities,
              :only => [:index, :new, :create]

    root 'pages#home'
  end

  # *.inspiredcauses.com => Campaign Subdomains
  constraints(lambda { |request| request.subdomain != 'www' }) do
    resources :people do
      resources :notes,
                :except => [:update, :edit]
      
      resources :messages,
                :only => [:index, :show]
    end

    resources :companies do
      resources :notes,
                :except => [:update, :edit]
    end

    resources :messages,
              :except => [:edit, :update, :destroy]

    resources :digital_addresses,
              :only => [:destroy]

    resources :communities,
              :only => [:show, :update] do
      resources :notes,
                :except => [:update, :edit]
    end

    get '/edit', to: 'communities#edit', as: :owner_edit_community
    root :to => "communities#show", as: :community_home
  end
end

app/models/community.rb
class Community < ActiveRecord::Base
	has_many :people
	has_many :companies
	has_many :messages

	belongs_to :address
	belongs_to :owner, :class_name => "User"

	has_many :community_users
	has_many :users, through: :community_users
	has_many :digital_addresses, as: :addressable, :dependent => :destroy
	has_many :notes, as: :noteable, :dependent => :destroy

	accepts_nested_attributes_for :digital_addresses
	accepts_nested_attributes_for :address

	mount_uploader :photo, ProfilePhotoUploader

	validates_presence_of :name,
                        :subdomain,
                        :user_ids

	validates_uniqueness_of :name,
                       	  :subdomain
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_community_from_subdomain, only: [:show, :edit, :update]
  before_action :ensure_user_can_edit_community, only: [:edit, :update]

  # GET /communities
  # GET /communities.json
  def index
    @communities = current_user.communities.all

    @page_title       = "Communities"
    @page_subtitle    = "Uniting People and Companies"
    @page_description = ""
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
    @noteable   = @community
    @note       = @community.notes.new
    @notes      = @community.notes.order("created_at desc")

    @tab_name         = "community_home"
    @page_title       = "#{@community.name}"
    @page_subtitle    = "Community Home"
    @page_description = ""
  end

  # GET /communities/new
  def new
    @community = Community.new
    @community.owner = current_user
    @community.user_ids = [current_user.id]
    @community.build_address
    @community.digital_addresses.build
    @community.digital_addresses.build

    @page_title       = "New Community"
    @page_subtitle    = "Your Store Information"
    @page_description = ""
  end

  # GET /communities/1/edit
  def edit
    unless @community.address.present?
      @community.build_address
    end

    unless @community.digital_addresses.present?
      @community.digital_addresses.build
    end

    @page_title       = "Edit #{@community.name}"
    @page_subtitle    = "Update Community Information"
    @page_description = ""
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to community_home_url(:subdomain => @community.subdomain), notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to community_home_url(:subdomain => @community.subdomain), notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    def ensure_user_can_edit_community
      unless @community.owner == current_user
        redirect_to community_home_path, notice: "Only Administrator can make this edit."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:name,
                                        :subdomain,
                                        :owner_id,
                                        :photo,
                                        :remote_photo_url,
                                        :is_active,
                                        { :user_ids => [] },
                                        digital_addresses_attributes: [:id, :name, :address_type, :url],
                                        address_attributes: [:id, :street_line_1, :street_line_2, :city, :state, :zip])
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.erb
<%= simple_form_for(@community, :html => {:multipart => true}) do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="col-md-6">

      <legend>General Information</legend>
      <%= f.input :name, :label => "Store Name" %>
      <% unless @community.id %>
        <%= f.input :subdomain %>
      <% end %>
      
      <div class="row">
        <div class="col-md-6">
          <%= f.input :photo, :label => "Upload Photo from File" %>
          <%= f.hidden_field :photo_cache %>
        </div>
        <div class="col-md-6">
          <%= f.input :remote_photo_url, :label => "or from URL (http://...)" %>
        </div>
      </div>
      
      <%= f.association :users, :label => "Team", label_method: :email, input_method: :id %>

      <legend>Digital Addresses</legend>
      <div class="">
        <table id="digital_address_table" class="full_width">
          <tr>
            <th>Reference</th>
            <th>Type</th>
            <th class="remove_button_column"></th>
          </tr>
          <%= f.association :digital_addresses do |d_address| %>
            <tr>
              <td><%= d_address.input :url, label: false %></td>
              <td><%= d_address.input :address_type, collection: (DigitalAddress.address_types), label_method: :last, value_method: :first, input_html: { :class => "form-control"}, :label => false %></td>
            </tr>
          <% end %>
        </table>
        <div class="text-right">
          <%= link_to "", :onClick => "return false;", :id => "add_web_button", :class => "btn btn-sm btn-default pull-right" do %>
            <div class="glyphicon glyphicon-plus"></div> Add Web Address
          <% end %>
        </div>
      </div>
    
    </div>
    <div class="col-md-6">

      <legend>Physical Address</legend>
      <%= f.association :address do |a| %>
        <div class="row">
          <div class="col-md-12">
            <%= a.input :street_line_1 %>
          </div>
          <div class="col-md-12">
            <%= a.input :street_line_2 %>
          </div>
          <div class="col-md-5">
            <%= a.input :city, :placeholder => "Atlanta" %>
          </div>
          <div class="col-md-4">
            <%= a.input :state, collection: (Address.states), :prompt => 'State...', input_html: { :class => "form-control"} %>
          </div>
          <div class="col-md-3">
            <%= a.input :zip, :placeholder => "30303" %>
          </div>
        </div>
      <% end %>

      <div class="form-actions">
        <%= f.button :submit, :class => "btn btn-primary pull-right" %>
      </div>
  
    </div>
  </div>
<% end %>

<%= content_for :page_script do %>
  <script type="text/javascript">
    var subdomain = document.getElementById("community_subdomain");

    $("#community_name").keyup(function() {
      var user_first_name = document.getElementById("community_subdomain");
      subdomain.value = this.value.toLowerCase().replace(/\s/g, '');
    });
  </script>

  <script type="text/javascript">
    // Add Digital Address Script
    $(document).ready(function(){
      var i = <%= @community.digital_addresses.count %>;
      var options = '<%= raw options_from_collection_for_select(DigitalAddress.address_types, :first, :last).squish.gsub('> <', '><') %>';

      $("#add_web_button").click(function(){
        i ++;
        $("#digital_address_table").append('<tr id="digi_'+i+'""><td><div class="input url optional community_digital_addresses_url"><input class="string url optional" id="community_digital_addresses_attributes_'+i+'_url" name="community[digital_addresses_attributes]['+i+'][url]" type="url"></div></td><td><select id="community_digital_addresses_attributes_'+i+'_address_type" name="community[digital_addresses_attributes]['+i+'][address_type]" class="form-control">' + options + '</select></td><td><div class="remove_column">x</div></td></tr>');
      });
    });
  </script>
  <script type="text/javascript">
    // Remove Row Script
    $(document).ready(function(){
      $('table').on('click', '.remove_column', function(e){
         $(this).closest('tr').remove()
      })
    });
  </script>
<% end %>

app/views/communities/_tabs.html.erb
<!-- Nav tabs -->
<ul class="nav nav-tabs">
  <li><div class="tab-text">Recent:</div></li>
  <li class="active"><a href="#notes" data-toggle="tab"><div class="icon-noteslist"></div> Notes</a></li>
  <li><a href="#messages" data-toggle="tab"><div class="icon-map-marker"></div> Messages</a></li>
  <li class="pull-right"><%= link_to "Edit #{@community.name}", owner_edit_community_path %></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div class="tab-pane active" id="notes">
    <div class="row">
      <div class="col-sm-6 col-md-7">
        <%= render @notes.last(5) if @notes %>
      </div>
      <div class="col-sm-6 col-md-5">
        <div class="new_note_wrapper">
          <h3 class="new_note_heading">New Note</h3>
          <%= render "notes/form" %>
        </div>
      </div>
    </div>
  </div>
  <div class="tab-pane" id="messages">
    <%= render @community.messages %>
    <p class="text-center">
      <%= link_to "View All Messages", messages_path %>
    </p>
  </div>
</div>

app/views/communities/edit.html.erb
<%= render 'form' %>

app/views/communities/index.html.erb
<%= link_to 'New Community', new_community_path, :class => "btn btn-primary pull-right" %><br>
<hr>

<div class="row">
  <% if @communities.count > 0 %>
    <% @communities.order("name asc").each do |community| %>
      <div class="col-xs-6 col-sm-4 col-md-3">
        <%= link_to community_home_url(:subdomain => community.subdomain) do %>
          <div class="asset_preview">
            <% if community.photo.present? %>
              <%= image_tag community.photo_url(:medium), :class => "asset_img" %>
            <% else %>
              <%= image_tag "default_company.png", :class => "asset_img" %>
            <% end %>

            <div>
              <h2><%= community.name %></h2>

              <div class="asset_preview_social text-center">
                <% community.digital_addresses.order("address_type asc").each do |digi| %>
                  <%= link_to digi.link_to, :target => "_blank" do %>
                    <div class="<%= digi.icon %>"></div>
                  <% end %>
                <% end %>
              </div>

              <div class="btn-group btn-group-justified">
                <%= link_to 'Enter', community_home_url(:subdomain => community.subdomain), :class => "btn btn-primary" %>
                <% if community.owner == current_user %>
                  <%= link_to 'Edit', owner_edit_community_url(:subdomain => community.subdomain), :class => "btn btn-primary" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="text-center">
      <p>You don't have access to any Communities.</p>
      <p><%= link_to "Add a Company", new_company_path %></p>
    </div>
  <% end %>
</div>

app/views/communities/new.html.erb
<%= render 'form' %>

app/views/communities/show.html.erb
<div class="row">
  <div class="col-md-3">

    <%= render partial: "shared/asset_details", locals: {:asset => @community} %>

  </div>
  <div class="col-md-9">
    <%= render "communities/tabs" %>
  </div>
</div>