config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  constraints(lambda { |request| request.subdomain.empty? or request.subdomain == 'www' }) do
    resources :communities,
              :only => [:index, :new, :create]

    root 'pages#home'
  end

  # *.inspiredcauses.com => Campaign Subdomains
  constraints(lambda { |request| request.subdomain != 'www' }) do
    resources :people do
      resources :notes,
                :except => [:update, :edit]
      
      resources :messages,
                :only => [:index, :show]
    end

    resources :companies do
      resources :notes,
                :except => [:update, :edit]
    end

    resources :messages,
              :except => [:edit, :update, :destroy]

    resources :digital_addresses,
              :only => [:destroy]

    resources :communities,
              :only => [:show, :update] do
      resources :notes,
                :except => [:update, :edit]
    end

    get '/edit', to: 'communities#edit', as: :owner_edit_community
    root :to => "communities#show", as: :community_home
  end
end

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>CFA Community</title>

<%= display_meta_tags :og => {
	:site_name   => "CFA Community",
  :title    	 => "#{@page_title} | #{@page_subtitle}",
  :description => "#{@page_description}",
  :url      	 => "#{request.original_url}",
  :prev        => "#{request.referer}"} %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

<%= csrf_meta_tags %>

<!-- For third-generation iPad with high-resolution Retina display: Size should be 144 x 144 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
<!-- For iPhone with high-resolution Retina display: Size should be 114 x 114 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
<!-- For first- and second-generation iPad: Size should be 72 x 72 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: Size should be 57 x 57 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
<!-- For all other devices Size should be 32 x 32 pixels -->
<%= favicon_link_tag 'favicon.png', :rel => 'shortcut icon' %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag "cfa-logo.png" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user and @community and @community.id %>
        <ul class="nav navbar-nav">
          <li class="<%= "active" if @tab_name == "community_home" %>">
            <%= link_to "Home", community_home_path %>
          </li>
          <li class="<%= "active" if @tab_name == "people" %>">
          	<%= link_to "People", people_path %>
          </li>
          <li class="<%= "active" if @tab_name == "companies" %>">
            <%= link_to "Companies", companies_path %>
          </li>
          <li class="<%= "active" if @tab_name == "messages" %>">
            <%= link_to "Messages", messages_path %>
          </li>
        </ul>
      <% end %>

      <%= render "layouts/nav_user" %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_user.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to communities_url(:subdomain => false) do %>
            <div class="icon-store"></div> Your Communities
          <% end %>
        </li>
        <li>
          <%= link_to edit_user_registration_url(:subdomain => false) do %>
            <div class="icon-cog"></div> Account Settings
          <% end %>
        </li>
        <li>
          <%= link_to new_user_invitation_path do %>
            <div class="icon-addfriend"></div> Invite Coworker
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_url(:subdomain => false), method: :delete do %>
            <div class="icon-exit"></div> Logout
          <% end %>
        </li>
      </ul>
    </li>
  <% else %>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
    <li><%= link_to "Login", new_user_session_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render "layouts/head" %>
</head>
<body>

<%= render "layouts/nav" %>

<div class="heading">
	<div class="container">
		<h1>
      <% if @page_subtitle.present? %>
        <small><%= @page_subtitle %></small><br>
      <% end %>
      <%= @page_title %>
    </h1>
	</div>
</div>

<div class="container main_container">
  <!-- Breadcrumb Titles are handles in the controller -->
  <% if render_breadcrumbs.present? %>
    <ol class="breadcrumb">
      <%= render_breadcrumbs :tag => :li, :separator => "" %>
    </ol>
  <% end %>
	<% if notice %><div class="alert alert-success"><%= notice %></div><% end %>
	<% if alert %><div class="alert alert-danger"><%= alert %></div><% end %>
	<%= yield %>
</div>

<footer class="footer">
</footer>

<%= yield(:page_script) %>

</body>
</html>